---
Gemfile:
  supports_windows: true
  required:
    ':system_tests':
      - gem: beaker-rspec
        git: https://github.com/petems/beaker-windows.git
        ref: 38227e3bec946dbd52ac4aece8d28af360a33cc4
      - gem: beaker
        git: https://github.com/petems/beaker-rspec-windows.git
        ref: d42d1b83b8de9c8b76fb5a19c859a3e71eeab28a
      - gem: beaker-puppet_install_helper
spec/spec_helper_acceptance.rb:
  windows: true
  dependencies:
    - puppetlabs-stdlib
    - puppetlabs-powershell
    - puppet-windowsfeature
spec/acceptance/nodesets/centos-511-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-66-x64-pe.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-66-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-72-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1204-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-server-1404-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/debian-78-x64.yml:
  unmanaged: true
spec/acceptance/nodesets/debian-82-x64.yml:
  unmanaged: true
.travis.yml:
  secure: "XeskI0qPXdnzw63JkJd6aSnaOY2OqD57hXhgJ8c8nq3h5cnMLXDRtyorFRAV+drXkt4q8rEyN+Bj8x9CtMOTY9t8GT5YLRG9T7mscFIPMU7pLSt4Gh25LRYtBwD5JBvX6XdGsHnjkQ8mIrponNy5xgF0a50dnSrIfL6W+6drt/k="
